### PR TITLE
Update makesmatheasy and documentation repo URL

### PR DESCRIPTION
**Pull request by sairish2001**
Transferred the Personal project to Organization.
So the URL changed

### CODE REVIEW

**Comment by sairish2001** [comment]
- @Vishal-raj-1 Kindly review this

**Review by Vishal-raj-1 — APPROVED** [review]

**Comment by Vishal-raj-1** [comment]
@sairish2001 did you update this in leaderboard page as well ?

**Comment by sairish2001** [comment]
@Vishal-raj-1 Yes, Praveen sir merged the PR in leaderboard js file

**Comment by sairish2001** [comment]
https://github.com/praveenscience/GSSoC21-Leaderboard-Projects/pull/11

refer this

**Comment by sairish2001** [comment]
@Vishal-raj-1 Can you please merge?

**Pull request merged**
